### ISSUE TITLE
--no-cipher-alpn or --force-openssl does not disable 

### ISSUE THREAD

**Issue by bbaassssiiee** [OWASP/O-Saft#100]
[workspace] $ /bin/bash -xe /home/jenkins/tmp/jenkins3421667750711307123.sh
+ ./o-saft.pl --no-warning --no-cipher-alpn --force-openssl --no_header +vulns schipol.nl --legacy=compact
**WARNING: 126: improper Net::SSLeay version; tests with/for ALPN disabled at ./o-saft.pl line 2000.
!!Hint: --no-cipher-alpn or --force-openssl can be used to disable this check
!!Hint: use options like: --v --trace
!!Hint: use options like: --v --trace
!!Hint: use options like: --v --trace
!!Hint: use options like: --v --trace

**Comment by EnDe** [comment]
thanks.

I'll check if the Hint message needs to be corrected.

**Comment by EnDe** [comment]
can you please post the result of:

  o-saft.pl --version|egrep -i '(::SSLeay|openssl)'

**Comment by bbaassssiiee** [comment]
```

*WARNING: 145: openssl s_client does not support '-serverinfo'; checks without TLS extension disabled
**WARNING: 143: SSL version 'SSLv2': not supported by Net::SSLeay; not checked
**WARNING: 143: SSL version 'TLSv13': not supported by Net::SSLeay; not checked
    Net::SSLeay::
       ::OPENSSL_VERSION_NUMBER()    0x1000105f (268439647)
       ::SSLeay()                    0x1000105f (268439647)
    Net::SSLeay::SSLeay_version()    OpenSSL 1.0.1e-fips 11 Feb 2013
= openssl =
    external executable              /bin/openssl
    version of external executable   OpenSSL 1.0.1e-fips 11 Feb 2013
    full path to openssl.cnf file    <<undef>>
    common openssl.cnf files         /usr/lib/ssl/openssl.cnf /etc/ssl/openssl.cnf /System//Library/OpenSS/openssl.cnf /usr/ssl/openssl.cnf
    common paths to PEM files for CAs /etc/ssl/certs /usr/lib/certs /System/Library/OpenSSL
    openssl supported SSL versions   SSLv3 TLSv1 TLSv11 TLSv12
    Net::SSLeay            1.81     /usr/local/lib64/perl5/Net/SSLeay.pm
```

**Comment by EnDe** [comment]
Hmm, sounds like there is another problem beside the missleading text in the Hint message. After getting the new version of o-saft-dbx.pm, can you please post the results of
```
  o-saft.pl --v --v +version|grep Net::SSLeay
  o-saft.pl --v +quit|sed -n '/HASH:/,/HASH:/p'
```

**Comment by EnDe** [comment]
Fixed in [o-saft.pl](https://github.com/OWASP/O-Saft/commit/3bc25937e43dbc35f20b62e3d7def6096ae1d459).
The hint message was wrong; corrected.
The check for the warnings and hints has also been improved.
