### ISSUE TITLE
[Dockerfile]SSLeay not building with old protocol support

### ISSUE THREAD

**Issue by jerbasco1** [OWASP/O-Saft#102]
Can the dockerfile be updated to build SSLeay with SSLv2 and SSLv3 support as mentioned in:
[O-Saft docs Example:_Compile_Net::SSLeay](https://www.owasp.org/index.php/O-Saft/Documentation#Example:_Compile_Net::SSLeay)

error in o-saft.tcl
```
**WARNING: 143: SSL version 'SSLv2': not supported by Net::SSLeay; not checked
**WARNING: 143: SSL version 'SSLv3': not supported by Net::SSLeay; not checked
**WARNING: 143: SSL version 'TLSv13': not supported by Net::SSLeay; not checked
```

**Comment by EnDe** [comment]
Fixed with [Dockerfile](https://github.com/OWASP/O-Saft/commit/3754fbb0fcf98c99cdf5271a3c0fd920797cd9a1).

Note that this should support SSLv2 and SSLv3 but not TLSv1.3 )because that is still not implemented in openssl).

**Comment by jerbasco1** [comment]
Wow, that was fast.  Great work!
