### ISSUE TITLE
Missing files declared on Makefile

### ISSUE THREAD

**Issue by samueloph** [OWASP/O-Saft#112]
The following files are listed on the Makefile but are not present on the source code:

Should be at OSaft/Doc/:
* misc.txt

The next ones should be at Osaft/:
* _ciphers_osaft.pm
* _ciphers_iana.pm
*  _ciphers_openssl_all.pm
*  _ciphers_openssl_low.pm
*  _ciphers_openssl_medium.pm
*  _ciphers_openssl_high.pm

I'm not sure if some of them are supposed to be generated with another target before running the install one.

Thanks

**Comment by EnDe** [comment]
misc.txt added

**Comment by EnDe** [comment]
All files OSaft/_ciphers_*pm removed from SRC.pm in Makefile now.
The files are listed in the Makefile but are currently not used anywhere.
