### ISSUE TITLE
How to scan on custom ports?

### ISSUE THREAD

**Issue by bc-venkata** [OWASP/O-Saft#115]

**Comment by EnDe** [comment]
`o-saft.pl you.tld:4443 ...`
`o-saft.pl --port=4443 your.tld ...`
`o-saft.pl --port 4443 your.tld ...`
`o-saft.pl -port=4443 your.tld ...    # not recommended`
`o-saft.pl -port 4443 your.tld ...    # not recommended`
`o-saft.pl --p 4443 your.tld ... `

Note that --port and alike must preceed the hostname, see section "Options for all commands" in
`o-saft.pl --help=options`

**Comment by EnDe** [comment]
and:
`o-saft.pl https://your.tld:4443 ...`
