### ISSUE TITLE
+check crashes with old Net::SSLeay

### ISSUE THREAD

**Issue by achim-owasp** [OWASP/O-Saft#121]
o-saft.pl +check some.tld crashes with following error:
``**WARNING: 655: Net::SSLeay >= 1.46 required for getting some certificate checks at Net/SSLinfo.pm line 2384.
Can't locate auto/Net/SSLeay/P_alpn_sele.al in @INC (@INC contains: . ./lib  /bin /Library/Perl/Updates/5.10.0 /System/Library/Perl/5.10.0/darwin-thread-multi-2level /System/Library/Perl/5.10.0 /Library/Perl/5.10.0/darwin-thread-multi-2level /Library/Perl/5.10.0 /Network/Library/Perl/5.10.0/darwin-thread-multi-2level /Network/Library/Perl/5.10.0 /Network/Library/Perl /System/Library/Perl/Extras/5.10.0/darwin-thread-multi-2level /System/Library/Perl/Extras/5.10.0 .) at o-saft.pl line 4397`

**Comment by EnDe** [comment]
Fixed in [o-saft.pl](https://github.com/OWASP/O-Saft/commit/9cf9dd8b9c7ff7ba33496dd7ad5784eb29401e5c).
