### ISSUE TITLE
incomplete error message

### ISSUE THREAD

**Issue by achim-owasp** [OWASP/O-Saft#122]
o-saft.pl +protocols some.tld  returns following incomlete warning message
`**WARNING: 081: ancient Net::SSLeay 1.35 < 1.49; cannot use ::initialize at Net/SSLinfo.pm line 683.
**WARNING: 135:  < 1.49; may throw warnings and/or results may be missing; at o-saft.pl line 2247.`

**Comment by EnDe** [comment]
Fixed in [o-saft.pl](https://github.com/OWASP/O-Saft/commit/8beb79964e626905e3d16a34c26dc256330492e6).
