### ISSUE TITLE
check for logjam vulnerability seems to be wrong

### ISSUE THREAD

**Issue by achim-owasp** [OWASP/O-Saft#123]
o-saft.pl +logjam some.tld
returns
`Connection is safe against Logjam attack:	yes`
even if some.tld allows EXPORT ciphers

**Comment by EnDe** [comment]
Fixed in [o-saft.pl](https://github.com/OWASP/O-Saft/commit/a1ba50490e45e3dd61d91e5290fe977fc24e8d45).
