### ISSUE TITLE
o-saft.cgi rejects some harmless parameters

### ISSUE THREAD

**Issue by achim-owasp** [OWASP/O-Saft#125]
o-saft.cgi --cgi  --host=some.tld --cmd=+cn --exit=BEGIN0
fails, does not execute o-saft.pl

**Comment by EnDe** [comment]
this is a bug, but the check for malicious arguments fails only if the last argument end with a digit

**Comment by EnDe** [comment]
Issue documented internal in [o-saft.cgi](https://github.com/OWASP/O-Saft/blob/master/o-saft.cgi).

**Comment by EnDe** [comment]
Looking pedantically it's a bug, but it may occour in rare situations only, and only when testing. It should not occour when used as real CGI as there it must be the very last parameter from the corresponding web page.
Hence I leave the issue closed and label is as "enhancement" instead of "bug".
