### ISSUE TITLE
.o-saft.pl does not read host entries without a "-" (OS: Win+Linux)

### ISSUE THREAD

**Issue by Benemonaco** [OWASP/O-Saft#127]
Hostentries in the .o-saft.pl file aren't read if the hostname doesn't include a "-", same goes for ip-addresses.
i.e: 8.8.8.8 / www.google.de is not working
--HOST=host:port is working as intended.

Tested Versions:
Win 10: O-Saft version: 20.06.06
Kali: O-Saft: 19.01.19

**Comment by EnDe** [comment]
problem cannot be repsoduces, can you please post your --host= entries from your .o-saft.pl verbatime here
Thanks.

**Comment by EnDe** [comment]
no feedback in three yeas, closed
