### ISSUE TITLE
Use another variable assignment with a combined operator

### ISSUE THREAD

**Issue by elfring** [OWASP/O-Saft#129]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of combined operators](https://perldoc.perl.org/perlop#Assignment-Operators "Description for assignment operators") accordingly.

```diff
diff --git a/checkAllCiphers.pl b/checkAllCiphers.pl
index 89704cc..82d2144 100755
--- a/checkAllCiphers.pl
+++ b/checkAllCiphers.pl
@@ -264,7 +264,7 @@ while ($#argv >= 0) {
     if ($arg =~ /^--trace([_-]?cmd)$/i)                 { $cfg{'traceCMD'}++;    next; } # ..
     if ($arg =~ /^--trace(@|[_-]?key)$/i)               { $cfg{'traceKEY'}++;    next; } # ..
     if ($arg =~ /^--trace=(\d+)$/i)                     { $cfg{'trace'}    = $1; next; }
-    if ($arg =~ /^--trace([_-]?time)$/i)                { $cfg{'traceTIME'}++;   $cfg{'trace'} = $cfg{'trace'}||1; next; } # Timestamp on; trace on if it was off
+    if ($arg =~ /^--trace([_-]?time)$/i)                { $cfg{'traceTIME'}++;   $cfg{'trace'} ||= 1; next; } # Timestamp on; trace on if it was off
     if ($arg =~ /^--?p(?:ort)?=(\d+)$/i)                { $cfg{'port'}     = $1; next; }
     if ($arg =~ /^--?h(?:ost)?=(.+)$/i)                 { push(@{$cfg{'hosts'}}, $1 . ":" . ($cfg{'port'}||443)); next; }     
     # proxy options
```

**Comment by EnDe** [comment]
fixed checkALLCiphers.pl 1.27

**Comment by elfring** [comment]
Thanks for [your integration of another source code improvement](https://github.com/OWASP/O-Saft/commit/2e0a13c1fc68dad57a1a678b39304defb0415cff "trace variable assignment improved").

**Comment by elfring** [comment]
💭 Would you become interested to achieve similar code adjustments with more advanced transformation tools?

**Comment by EnDe** [comment]
Yes for sure. I'm not really happy with perlcritic, which is currently used.
Just to not: must run locally.

**Comment by elfring** [comment]
💭 Do you get any further development ideas from similar transformation suggestions which I published for various software components?
