### ISSUE TITLE
Change hardcoded perl path to use env

### ISSUE THREAD

**Issue by noaxispoint** [OWASP/O-Saft#130]
Please look at changing the hardcoded perl path of /usr/bin/perl to using env.

For example:

`#!/usr/bin/perl`

to

`#!/usr/bin/env perl`

**Comment by EnDe** [comment]
This seams to be a valid requirement for users.
Unfortunatelly "env perl" (or any other program) does not allow using additional arguments.
Using arguments to the called interpreter is often used during development, make developers live easier;)

I will add an option to the INSATALL.sh, so the user may get her/his behaviour.

Anyway, this requirement also showed me that there needs to be some clean-up about hashbang usages.

**Comment by EnDe** [comment]
Description about pros&cons of /usr/bin/env added to [docs/concepts.txt](https://github.com/OWASP/O-Saft/commit/32a23ad56826ec9a482e110cfb5cc5f9793ff0e7), see "Using env" there.
New option --useenv implemented in [INSTALL.sh](https://github.com/OWASP/O-Saft/commit/c4e5e0363efe0a8bc06b1082e3f3d3d2748a4c2b).
Another option --usegnuenv for INSTALL.sh comming soon ...

**Comment by EnDe** [comment]
Additional option --gnuenv implemented in [INSTALL.sh](https://github.com/OWASP/O-Saft/commit/af9ac4b50ba059ddfd6ebe931de5ff4bc95b1399)
