### ISSUE TITLE
"up to 65535 per SSL protocol"

### ISSUE THREAD

**Issue by kylak** [OWASP/O-Saft#138]
Hi.

Could you explain please how you have "up to 65535" cipher suites "per SSL protocol" ?

I personally doesn't know any other cipher suite than [those 376 ones](https://docs.rs/rustls/latest/rustls/enum.CipherSuite.html).

Thanks.

**Comment by EnDe** [comment]
When go down to the wire and look at the communication there, a "cipher suite" is nothing else than 2 bytes = 2^16 = 65536
However, depending on the protocol it's actually 3 bytes = 2^24 ~16.7 million.
That's what you can check with the options --cipher-range=huge (2 bytes) and --cipher-range=full (3 bytes).
If some (most) of these numbers are known cipher suites, or is irrelevant. We can check it. 
You asked for fuzzing? this is some kind of fuzzing ;-)
If you use the --trace option, you'll see these 3-byte numbers which are part of each cipher hex key (last 3 bytes).

**Comment by kylak** [comment]
Ah ok I see that's great. Yes I asked for fuzzing.

**Comment by EnDe** [comment]
;-) Remember, if you have a server in your barn which didn't get updates since ages, your modern openssl, rusttls, whatever, ... on your client can't check old ciphers, even the server enabled them. Be happy and feel safe with modern devsecops, continuous hourly updates, ... your security in the barn is broken, and you won't see it.
---
That's why I'm highly interested to get "your" panic error fixed.

**Comment by kylak** [comment]
Ok. I currently have a network problem. When the network is repaired I'll give you what you need to debug the panic error.

**Comment by kylak** [comment]
Hello, 

You said regarding cipher suite that "depending on the protocol it's actually 3 bytes".

However, I didn't find a SSL/TLS version protocol having 3 bytes for the cipher suite, but If found for them all 2 bytes.
But maybe I have missed something ? 

Please to which SSL/TLS version protocol are you referring when talking about 3 bytes ?

Thanks.

**Comment by kylak** [comment]
Hello,

You said regarding cipher suite that "depending on the protocol it's actually 3 bytes".

However, I didn't find a SSL/TLS version protocol having 3 bytes for the cipher suite, but If found for them all 2 bytes.
But maybe I have missed something ?

Please to which SSL/TLS version protocol are you referring when talking about 3 bytes ?

Thanks.

**Comment by EnDe** [comment]
SSLv2, for example
  0x01,0x00,0x80 - RC4-MD5
  0x06,0x00,0x40 - DES-CBC-MD5
 ...
see (ancient openssl 0.9x):
openssl ciphers -V ALL:EXP:NULL

**Comment by kylak** [comment]
But there's only SSL2 right ?

**Comment by EnDe** [comment]
> But there's only SSL2, right ?

AFAIK yes

> I don't have the ancient openssl 0.9x, if you have it, ..

see [usr/install_openssl.sh](/OWASP/O-Saft/blob/master/usr/install_openssl.sh)

**Comment by kylak** [comment]
Ok. Thanks.

Therefore, it doesn't make sense to do a --range=full on a protocol that is not SSLv2, and thus we shouldn't do it.

And do we agree that the --range=full mode is the best to test all the cipher suite possible of SSLv2 ?

**Comment by EnDe** [comment]
hmm, please make yourself used to the defined ranges first:
  `./o-saft.pl --help=ranges`

Then you see that --range=full does not cover 3-byte SSLv2 ciphers.
Hence it's the opposite of what you ask: --range=full makes sense with anything except SSLv2.
BUT, keep in mind that there's no restriction that a target supports any cipher for any protocol, whether there is a valid RFC or not.

For testing SSLv2, I'd (currently) recommend --range=SSLv2 .

However, this brings up other test cases for me, I'll think about more ranges ...

> ... and thus we shouldn't do it.

hmm, why?
Do you believe what is defined or what someone (CEO, admin, a priest) claims should be?
This tool is build to test as accurate as possible what the target provides, which is most often different to a belief. We're drifting away to philosophical discussions ...

**Comment by kylak** [comment]
> hmm, please make yourself used to the defined ranges first:
./o-saft.pl --help=ranges

I broke the help option, cf. [here](https://github.com/OWASP/O-Saft/issues/157).

> BUT, keep in mind that there's no restriction that a target supports any cipher for any protocol, whether there is a valid RFC or not.

Does this means that a cipher suite from the full range could be used by SSLv2 ? If it means that, then why the full range couldn't be used for SSLv2 ? It would make sense to use this range with SSLv2 if SSLv2 could accept a cipher suite from this range. No ?

> hmm, why?
Do you believe what is defined or what someone (CEO, admin, a priest) claims should be?
This tool is build to test as accurate as possible what the target provides, which is most often different to a belief.

Got it. The huge range mode will test all RFC defined possible combination for cipher suite id encoded on 2 bytes, meaning that if a SSL/TLS server is merely "correctly" configured (meaning as defined in the RFC), then ONLY the "huge" range mode has to be used to know which cipher suite (for a protocol version which is different than SSLv2) is accepted by the server.
Now, if you want to see if the server has implemented their owned version of SSL/TLS, then you might try cipher suite id encoded on 3 bytes, who know maybe they chose in their implementation to encode the cipher suite id on 3 bytes rather than 2 ? And so, if you want to see if their own personal version of SSL/TLS uses 3 bytes to encode cipher suite id, and you think that this own personal version of SSL/TLS is probably the same than the others except for cipher suite id encoding, then there is the full range mode to help you. So am I correct? is it this the sense of the full range mode?

**Comment by EnDe** [comment]
> Does this means that a cipher suite from the full range could be used by SSLv2 ? 

yes (see range=SSLv2)

> why the full range couldn't be used for SSLv2 

I wrote "doesn't make sense" and not "couldn't be used". You can use any range for any protocol. It's just the special 2-byte cipher suites which will not work with other protocols.
Reason is that our communication with the target uses a very basic TLS protocol. TLS allows 2-bytes per cipher only, hence the 3-byte ciphers are omitted then. 

> ... SSLv2 could accept a cipher suite from this range.

yes, this could be tested.
Would be happy, if someone tests this more extensively (`--trace=4` is your friend then ;-)

> The huge range mode will test all RFC defined possible combination ...

yes

> ..  has implemented their owned version of SSL/TLS ...

As long as the basic protocol (the first 3-way handshake) is SSL/TLS as defined in the standards, then it could be tested with o-saft.

Any other "own implementation" is hard to test, this goes more in the direction of fuzzzing the protocol. That's the domain of other tools like [TLS-attacker](https://github.com/tls-attacker/TLS-Attacker).

> ...  is it this the sense of the full range mode?

the sense of each range is what the user, who uses it, has in mind;-)

**Comment by kylak** [comment]
Hmm.. so to fully test SSLv2 we should do the SSLv2 range mode plus the full range mode, right ?

I don't understand also why the full range mode starts at 0x03000000 ad not 0x00 and why it ends at 0x03FFFFFF and not 0xFFFFFF ? Why is there this 03 before the 24 bits?

**Comment by EnDe** [comment]
Hmm, do you want to participate in the project?
These are so many very internal questions. The answer is in the code.

> Why is there this 0x03 before the 24 bits?

because we distinguish SSLv2 and later protocols and ciphers according this byte (borrowed from SSL/TLS protocol, see all corresponding RFCs;-)

**Comment by kylak** [comment]
> Hmm, do you want to participate in the project?

I cannot now.

> The answer is in the code.

Would you know where I could find it easily ? Or maybe you meant "The answer will be in the code"?

> because we distinguish SSLv2 and later protocols and ciphers according this byte

Ok.
