### ISSUE TITLE
Undefined subroutine &SSLinfo::do_ssl_open

### ISSUE THREAD

**Issue by niall-san** [OWASP/O-Saft#140]
I have cloned the repository and am attempting to assess whether a host supports CBC ciphers using `+cbc`. 

The application currently throws the error shown below. I have also tried it against different hosts.

```
./o-saft.pl +cbc cbc.badssl.com:443
**WARNING: 409: SSLv2 does not support SNI; cipher checks are done without SNI
**WARNING: 409: SSLv3 does not support SNI; cipher checks are done without SNI
Undefined subroutine &SSLinfo::do_ssl_open called at ./o-saft.pl line 2763.
```

This issue also seems to occur for `+des`, `+null`, `+adh`, `+export`.

**Comment by EnDe** [comment]
Looks like an "old" version, did you install the tarball from releases or from master?
Please post result of
 `grep 'SID_main ' o-saft.pl`

**Comment by niall-san** [comment]
I ran git clone against the repository from master. The output of that command is:

```
$ grep 'SID_main ' o-saft.pl
our $SID_main   = "@(#) o-saft.pl 3.85 24/07/18 21:54:21"; # version of this file
```

**Comment by EnDe** [comment]
should be fixed in [o-saft.pl](https://github.com/OWASP/O-Saft/blob/master/o-saft.pl).

you need to clone just this file.
Thanks for reporting.

**Comment by niall-san** [comment]
I have pulled the latest change and can confirm that I no longer receive the error. Thank you for fixing this.

**Comment by EnDe** [comment]
another fixed related to this issue: [lib/OCfg.pm](https://github.com/OWASP/O-Saft/blob/master/lib/OCfg.pm)

**Comment by EnDe** [comment]
closed.
