### ISSUE TITLE
... deprecated syntax ... lib/OTrace.pm line 415, 416

### ISSUE THREAD

**Issue by EnDe** [OWASP/O-Saft#142]
as reported by @kylak in [issue 137](/OWASP/O-Saft/issues/137):

executed `?./o-saft.pl --version` and got:

`
= Required (and used) Modules =
=   module name            VERSION  found in
=   ----------------------+--------+------------------------------------------
    IO::Socket::INET       1.33     /usr/lib64/perl5/IO/Socket/INET.pm
    IO::Socket::SSL        1.94     /usr/share/perl5/vendor_perl/IO/Socket/SSL.pm
    Time::Local            1.2300   /usr/share/perl5/vendor_perl/Time/Local.pm
    Net::DNS               0.72     /usr/lib64/perl5/vendor_perl/Net/DNS.pm
    Net::SSLeay            1.55     /usr/lib64/perl5/vendor_perl/Net/SSLeay.pm
    Ciphers                24.06.24 lib/Ciphers.pm
    OCfg                   24.06.24 lib/OCfg.pm
    OData                  24.06.24 lib/OData.pm
    ODoc                   24.06.24 <<not loaded>>
    error_handler          24.01.24 lib/error_handler.pm
    SSLinfo                24.06.24 lib/SSLinfo.pm
    SSLhello               24.06.24 lib/SSLhello.pm
    OMan                   24.06.24 <<not loaded>>
    OText                  24.06.24 lib/OText.pm
Having no space between pattern and following word is deprecated at lib/OTrace.pm line 415.
Bareword found where operator expected at lib/OTrace.pm line 415, near "s/(}[;,])?\s*$//gn"
Unquoted string "n" may clash with future reserved word at lib/OTrace.pm line 415.
Having no space between pattern and following word is deprecated at lib/OTrace.pm line 416.
Bareword found where operator expected at lib/OTrace.pm line 416, near "s/use\s*(strict|warnings);//gn"
Unquoted string "n" may clash with future reserved word at lib/OTrace.pm line 416.
syntax error at lib/OTrace.pm line 415, near "s/(}[;,])?\s*$//gn"
syntax error at lib/OTrace.pm line 416, near "s/use\s*(strict|warnings);//gn"
Execution of lib/OTrace.pm aborted due to compilation errors.
    OTrace                          <<not loaded>>
    OUsr                   24.06.24 <<not loaded>>
!!Hint: use '--v' to get list of all modules
`

**Comment by EnDe** [comment]
Bug in OTrace.pm which uses RegEx syntax supported by Perl > v5.22.0

**Comment by EnDe** [comment]
should be fixed in [lib/OTrace.pm](/OWASP/O-Saft/blob/master/lib/OTrace.pm).

**Comment by kylak** [comment]
I updated [lib/OTrace.pm](https://github.com/OWASP/O-Saft/blob/master/lib/OTrace.pm) and here is what I have now running ``./o-saft.pl --version`` :
```
= Required (and used) Modules =
=   module name            VERSION  found in
=   ----------------------+--------+------------------------------------------
    IO::Socket::INET       1.33     /usr/lib64/perl5/IO/Socket/INET.pm
    IO::Socket::SSL        1.94     /usr/share/perl5/vendor_perl/IO/Socket/SSL.pm
    Time::Local            1.2300   /usr/share/perl5/vendor_perl/Time/Local.pm
    Net::DNS               0.72     /usr/lib64/perl5/vendor_perl/Net/DNS.pm
    Net::SSLeay            1.94     /usr/local/lib64/perl5/Net/SSLeay.pm
    Ciphers                24.06.24 lib/Ciphers.pm
    OCfg                   24.06.24 lib/OCfg.pm
    OData                  24.06.24 lib/OData.pm
    ODoc                   24.06.24 <<not loaded>>
    error_handler          24.01.24 lib/error_handler.pm
    SSLinfo                24.06.24 lib/SSLinfo.pm
    SSLhello               24.06.24 lib/SSLhello.pm
    OMan                   24.06.24 <<not loaded>>
    OText                  24.06.24 lib/OText.pm
Can't exec "lib/OTrace.pm": Permission denied at ./o-saft.pl line 6194.
Use of uninitialized value $v in scalar chomp at ./o-saft.pl line 6196.
Use of uninitialized value $v in pattern match (m//) at ./o-saft.pl line 6197.
    OTrace                          <<not loaded>>
    OUsr                   24.06.24 <<not loaded>>
!!Hint: use '--v' to get list of all modules
```
Knowing that I executed ``./o-saft.pl --version`` with sudo.

**Comment by EnDe** [comment]
grrr, I hate git(hub), does not honor file bits properly ...

please do `chmod 555 ./lib/OTrace.pm` then error shoul go away

I've opened [issue 143](/OWASP/O-Saft/issues/143) for that.

**Comment by EnDe** [comment]
> ... and `sudo ...`

this tool works completely in user space, no root privileges required at all ;-)

**Comment by kylak** [comment]
So here what I have after having done the chmod : 
```
[...]
= Required (and used) Modules =
=   module name            VERSION  found in
=   ----------------------+--------+------------------------------------------
    IO::Socket::INET       1.33     /usr/lib64/perl5/IO/Socket/INET.pm
    IO::Socket::SSL        1.94     /usr/share/perl5/vendor_perl/IO/Socket/SSL.pm
    Time::Local            1.2300   /usr/share/perl5/vendor_perl/Time/Local.pm
    Net::DNS               0.72     /usr/lib64/perl5/vendor_perl/Net/DNS.pm
    Net::SSLeay            1.94     /usr/local/lib64/perl5/Net/SSLeay.pm
    Ciphers                24.06.24 lib/Ciphers.pm
    OCfg                   24.06.24 lib/OCfg.pm
    OData                  24.06.24 lib/OData.pm
    ODoc                   24.06.24 <<not loaded>>
    error_handler          24.01.24 lib/error_handler.pm
    SSLinfo                24.06.24 lib/SSLinfo.pm
    SSLhello               24.06.24 lib/SSLhello.pm
    OMan                   24.06.24 <<not loaded>>
    OText                  24.06.24 lib/OText.pm
    OTrace                 24.06.24 <<not loaded>>
    OUsr                   24.06.24 <<not loaded>>
!!Hint: use '--v' to get list of all modules
```

**Comment by EnDe** [comment]
ok, and what is the question with that?

**Comment by kylak** [comment]
There's none. It was simply to let you know the result (which is good I guess if ``<<not loaded>>`` is the normal/awaited statement).

**Comment by EnDe** [comment]
ok, I see the message needs to be improved;-)

**Comment by EnDe** [comment]
Message `not loaded` improved.
