### ISSUE TITLE
--cipher-range bizarre behaviour

### ISSUE THREAD

**Issue by kylak** [OWASP/O-Saft#150]
Hi.

When I do this command ``./o-saft.pl +cipher my.tld --ca-path=/etc/pki/tls --cipher-range=TLSv12`` I got 12 accepted cipher suites.

However when I switch the cipher-range to iana instead of TLSv12, I got 4 accepted cipher suites!

I don't understand, it seems to be a bug ..

**Comment by EnDe** [comment]
`--help-range` now prints number of ciphers per range, see [OMan.pm](/OWASP/O-Saft/blob/master/lib/OMan.pm).

**Comment by kylak** [comment]
Thanks, however I didn't find in the doc, the explanation of why iana has only 24 cipher suites because on their website they have more than 300 cipher suites.
