### ISSUE TITLE
I broke the help option

### ISSUE THREAD

**Issue by kylak** [OWASP/O-Saft#157]
If you do ``./o-saft.pl --help > help.txt`` it will break the help option.

**Comment by EnDe** [comment]
What do you mean by "break the help option"?

I can only think of following disruptive example
`./o-saft.pl --help > doc/help.txt` # which is like shooting in yourself in the foot
but even that would not break
Please clarify.

**Comment by kylak** [comment]
I mean that if I do ``./o-saft.pl --help > help.txt``, then ``./o-saft.pl --help` doesn't work anymore.

**Comment by EnDe** [comment]
as said: shooting yourself in the foot
a workaround, but not fully equivalent:
`./o-saft.pl --help|(sleep 1;cat>help.txt)`

Do you think that it's important to bother the user with warnings when trying to replace 191k by 180k help.txt ?
2'nd warning (in this case) would be that the file is potentially outdated
3'nd warning (in this case) would be that the file has a wrong checksum

`./o-saft.pl --help|more`

KISS- keep it simple secure

**Comment by EnDe** [comment]
Additional note: the behaviour of your initial example depends on many environmental "things", for example the used shell, the configuration of that shell, the underlaying file system.
Hence it won't be fixed in this project due to too many unknown dependencies.
