### ISSUE TITLE
documentation suggestion

### ISSUE THREAD

**Issue by kylak** [OWASP/O-Saft#158]
Since the documentation is **enormous**, it might be useful to give this documentation to an AI so that a user like me only has to ask the AI to answer his question, instead of trying to read the huge documentation. Could be very useful.

**Comment by EnDe** [comment]
NO!

**Comment by kylak** [comment]
Please, why ``NO!`` ?

**Comment by EnDe** [comment]
o-saft tests the reality, the facts. The documentation describes exactly that, no guess, no wish, no belief. If this documentation contains errors, they can be fixed.

AI gives potential answers according some not provable probability.
Recently checked one of the most mentioned AI engines, see [AI answer](https://osaft.pl/p/warum_SSL_TLS_bei_google_2024-06-22.png).

Find the error, it's easy :-]]

However, all user's are free to user their own tools, even AI, to ask it about o-saft. The answers are then not our responsibility.
Fair?
