### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by ieyring** [OWASP/O-Saft#39]
The script gives a "Out of Memory" everytime i try to start it. 
Perl-debugger teminates with "Out of Memory" :-)

Centos 5

**Comment by EnDe** [comment]
From Version 14.1.14 to 14.12.07 memory consumtion have been reduced.
If the problem ocours with the latest version, there's currently no simple fix, unfortunately. Sigh.
If you just want to check for ciphers, please use checkAllCiphers.pl which does not have such a memory problem.

Some memory is vasted when the %check structure is filled, see o-saft.pl below the line (ca. 622):
# now construct %checks from %check_* and set 'typ'
here the %check_* should be removed/deleted after copying.

Someone out to fix and test it?

**Comment by EnDe** [comment]
Quick fix available, see
https://github.com/OWASP/O-Saft/commit/d7d4e075d831e2f4ceced051ba40c66f5997dd0a

**Comment by EnDe** [comment]
Problem fixed, see https://github.com/OWASP/O-Saft/commit/5a2fd79054dddff5d24764330ec414d828a69c3c .
