### ISSUE TITLE
(experimental) Proxy-Feature for o-saft.pl is not working (SSLinfo fails)

### ISSUE THREAD

**Issue by sslHello** [OWASP/O-Saft#40]
SSLinfo fails, if the client tries to connect via a proxy:

o-saft.pl +info --proxyhost=proxy --proxyport=3128 www.server.tld --experimental --v --v --v --trace=3
...
#O-Saft :: cn_nosni: {
#Net::SSLinfo::do_ssl_open(www.server.tld,443,,)
#Net::SSLinfo::do_ssl_open cipherlist: ALL:NULL:eNULL:aNULL:LOW
#Net::SSLinfo::_check_host(www.server.tld)
#Net::SSLinfo::_check_host   .
#Net::SSLinfo::errors:do_ssl_open() failed calling _check_host(www.server.tld):
#Net::SSLinfo::do_ssl_open() failed.
#O-Saft :: cn_nosni:   }
#Net::SSLinfo::do_ssl_open(www.server.tld,443,,)
#Net::SSLinfo::do_ssl_open cipherlist: ALL:NULL:eNULL:aNULL:LOW
#Net::SSLinfo::_check_host(www.server.tld)
#Net::SSLinfo::_check_host   .
#Net::SSLinfo::errors:do_ssl_open() failed calling _check_host(www.server.tld): #Net::SSLinfo::errors:do_ssl_open() failed calling _check_host(www.server.tld):
#Net::SSLinfo::do_ssl_open() failed.
#Net::SSLinfo::_SSLinfo_get('errors',www.server.tld,443)
# do_ssl_open() failed calling _check_host(www.server.tld):
do_ssl_open() failed calling _check_host(www.server.tld):
**WARNING: Can't make a connection to www.server.tld:443; target ignored
#Net::SSLinfo::do_ssl_close(www.server.tld,443)
**WARNING: undefined Net::SSLinfo::socket; connection cannot be closed at Net/SSLinfo.pm line 1509.
#O-Saft :: done: www.server.tld

**Comment by EnDe** [comment]
please post output of:
   o-saft.pl +version

**Comment by sslHello** [comment]
I use the latest 'Test Version':
o-saft.pl 15.01.21
= Required (and used) Modules =
    IO::Socket::INET     1.35
    IO::Socket::SSL      1.998
    Net::SSLinfo         15.01.20
    Net::SSLhello        15.01.18
    Net::SSLeay          1.66

**Comment by sslHello** [comment]
Tested the Fix of 15.01.25 -> Fixed!
