### ISSUE TITLE
Proper Release

### ISSUE THREAD

**Issue by blshkv** [OWASP/O-Saft#42]
Please release the tool properly. It should be available in the download tab, and not as a part of the repository itself.

**Comment by EnDe** [comment]
Are asking for https://github.com/OWASP/O-Saft or
https://www.owasp.org/index.php/O-Saft ?

Both have no "download tab". 
On github you find the current *stable* release as o-saft.tgz file and the development release as the usual "Download zip" button. at owasp.org you also find both links in the "Quick Download" section.

Does this answer your question?

**Comment by blshkv** [comment]
I'm talking about
https://github.com/OWASP/O-Saft/releases
Tab
The current release is 15.05.15 and it is not in there

"Git clone" will give you the latest source copy plus the o-saft.tgz file which after some wild guess happens to be the release.

So please remove it, tag a next version and make the release

**Comment by EnDe** [comment]
Tagged.

**Comment by blshkv** [comment]
Thanks, almost there: please remove o-saft.tgz from the repository as well.

**Comment by blshkv** [comment]
Ping?

Please open the bug and don't close until it is confirmed as close.
