### ISSUE TITLE
uninitialized value in subroutine entry at SSL.pm

### ISSUE THREAD

**Issue by blshkv** [OWASP/O-Saft#43]
perl ./o-saft.pl +info domain.com

I'm getting the following message:
Use of uninitialized value in subroutine entry at /usr/lib64/perl5/vendor_perl/5.20.1/IO/Socket/SSL.pm line 430.
invalid SSL_version specified at /usr/lib64/perl5/vendor_perl/5.20.1/IO/Socket/SSL.pm line 368.

Any ideas how to fix it?

**Comment by EnDe** [comment]
Workaround: use --no-sslv2 and/or --no-tlsv13 and/or --no-dtlsv1

This error essage occours if the underlaying SSL library does not support a specified/requested SSL version. The error messages is already documented, see
o-saft.pl --help=known
or https://www.owasp.org/index.php/O-Saft/Documentation#invalid_SSL_version_specified_at_...IO.2FSocket.2FSSL.pm

The online help (see prvious link) has an improved description now. Thanks for the hint.

**Comment by blshkv** [comment]
This sounds like a documented program crash and and not user-friendly. Is any better way to handle the error automatically?

I run this software to find which protocols are disabled, not other way around.

**Comment by EnDe** [comment]
o-saft.pl already does a couple of checks to identify what the underlaying system (libssl, libcrypto, perl modules etc.) support. Unfortunately this error comes from the used modules, here Socket::SSL .
It's really hard to guess what a system supports.  So this is primary a limitation of the underlaying system.

For a user-friendly solution, you need to run a test with SSL.pm and check if it bails out with an error for a specific SSL Version. That would require eval() in the code, which I try to avoid.

However, o-saft.pl has implemented hints and workarounds:
  * disable the not supported versions in your  .o-saft.pl  (very simple ;-)
  * check which versions are supported:  o-saft.pl +version

If this is not sufficent for "commodity", feel free to improve the code. Search for  "supported SSL versions" in o-saft.pl and see the foreach loop. I'm happy to implement better solutions (but please avoid eval() or system()).

Hope this helps.

**Comment by EnDe** [comment]
> I run this software to find which protocols are disabled, not other way around. 

Hmm, have your tried:
    o-saft.pl +protocol
    o-saft.pl +protocols   ## <== this is most likely what you want
    o-saft.pl +version | grep versions

Note: keep in mind that .o-saft.pl may be in use, to disable it use --no-rc

**Comment by EnDe** [comment]
Documentation improved (available at next release)
https://www.owasp.org/index.php/O-Saft/Documentation#Note_on_SSL_versions
