### ISSUE TITLE
Is O-Saft installed in Kali 2.x by default?

### ISSUE THREAD

**Issue by delta24** [OWASP/O-Saft#46]
I noticed that Kali 2.x doesn't have O-Saft already installed. Previous versions of Kali installed it by default.
Can anyone confirm? :)

**Comment by EnDe** [comment]
on Kali-2016.1 it is not preinstalled. But you simply get it with:
  apt install o-saft

Does this help?

**Comment by delta24** [comment]
Yes, I just wanted to confirm that. Thanks!
