### ISSUE TITLE
Adding an option to specify custom explicit TLS kickstart bytes

### ISSUE THREAD

**Issue by maaaaz** [OWASP/O-Saft#47]
Hello,

I'm cross-posting a feature request from https://github.com/rbsec/sslscan/ as `o-saft` and `sslscan` are the most popular tool for TLS assessment:

https://github.com/rbsec/sslscan/issues/84

Cheers !

**Comment by EnDe** [comment]
Hi, can cou please give an example where to use these bytes then. Thanks.

**Comment by maaaaz** [comment]
Sure.
In the most recent case I was facing (sorry I can't tell the technology name), the following sequence was followed :
1. The client connects to the server TCP port, the **3-way handshake** takes place
2. The client sends the **custom kickstart sequence** to the server, telling it to switch to SSL
3. The server returns a custom ack (not used thereafter) to the client, telling it has switched to SSL and ready
4. The client sends the `clienthello`, then a normal SSL session takes place

So you can understand that without the custom kickstart sequence you can't init a normal SSL session, the server hasn't been informed to switch to SSL.

Cheers.

**Comment by sslHello** [comment]
Hi,

STARTTLS is done by our internal library 'SSLhello.pm' that is maintained by me.
I use a finit state machine with up to 5 states that only needs to be customized to add new protocols.
The easiest way is to officially integrate the protocol that you request. 

To open it for any customized Input (at least 2 states are reasonable) is more work to do, and for now the internal syntax for an receive (rx) state is different from sending (tx) as it was easier for the procedure to handle.
I could add it to the fearure requests of 'checkAllCiphers.pl' (the lightweight interface to SSLhello.pm) and copy it later to 'o-saft.pl'.
Cheers

Here 2 examples of customizing the finit state machine including error handling:
my @starttls_matrix = 
        ( ["SMTP", 
            ".*?(?:^|\\n)220\\s",                       # Phase1: receive '220 smtp.server.com Simple Mail Transfer Service Ready'
            "EHLO o-saft.localhost\r\n",         # Phase2: send    'EHLO o-saft.localhost\r\n'         
            ".*?(?:^|\\n)250\\s",                       # Phase3: receive '250 smtp.server.com Hello o-saft.localhost'
            "STARTTLS\r\n",                          # Phase4: send    'STARTTLS'
            ".*?(?:^|\\n)220\\s",                       # Phase5: receive '220'
            ".*?(?:^|\\n)(?:421|450)\\s",           # Error1: temporary unreachable (too many connections); 450 Traffic is being throttled (connects per ip limit: ...), +454?
            ".*?(?:^|\\n)4[57]4\\s",                   # Error2: This SSL/TLS-Protocol is not supported 454 or 474
            ".*?(?:^|\\n)(?:451|50[023]|554)\\s",   # Error3: fatal Error/STARTTLS not supported: '500 Syntax error, command unrecognized', '502 Command not implemented', '503 TLS is not allowed',  554 PTR lookup failure ...
          ],
...
          ["LDAP",                                # found good hints at 'https://github.com/iSECPartners/sslyze/blob/master/utils/SSLyzeSSLConnection.py'$
            "",                                         # Phase1: receive -unused-$
            "",                                         # Phase2: send    -unused-$
            "",                                         # Phase3: receive -unused-$
            "0\x1d\x02\x01\x01w\x18\x80\x161.3.6.1.4.1.1466.20037", # Phase4: send    'STARTTLS'
            "0\\x24\\x02\\x01\\x01\\x78\\x1F\\x0A\\x01\\x00\\x04\\x00\\x04\\x00\\x8A\\x161\\.3\\.6\\.1\\.4\\.1\\.1466\\.20037",  # Phase5: receive 'Start TLS request accepted.'
            "",                                         # Error1: temporary unreachable (too many connections);
            "",                                         # Error2: This SSL/TLS-Protocol is not supported 
            "",                                         # Error3: fatal Error/STARTTLS not supported
          ],
...

**Comment by sslHello** [comment]
Hi,
I've just uploaded new versions of 'checkAllCiphers.pl' and 'Net/SSLhello.pm' that should realize your request. You can send hex values using "\x01\x02..." in sending phases 2 and/or 4 of my internal state machine. Please consider that it is new, experimental code.
Thank you for your proposal and please give me feedback if it works.
Kind regards

Text of the commit:
New option '--starttls=CUSTOM' to customize your own STARTTLS sequence including error handling, see 'checkAllCiphers.pl --h'
Example: checkAllCiphers.pl localhost:25 --starttlsphase[1]=".?(?:^|\n)220\s" --starttlsphase[2]="EHLO o-saft.localhost\r\n" --starttlsphase[3]=".?(?:^|\n)250\s" --starttlsphase[4]="STARTTLS\r\n" --starttlsphase[5]=".?(?:^|\n)220\s" --starttlserr[1]=".?(?:^|\n)(?:421|450)\s" --starttlserr[2]=".?(?:^|\n)4[57]4\s" --starttlserr[3]=".*?(?:^|\n)(?:451|50[023]|554)\s" --starttls=CUSTOM  --experimental

Extract of the new help of checkAllCiphers.pl:

    --starttls=STARTTLS_TYPE
                Use STARTTLS to start TLS. 
                STARTTLS_TYPE is any of SMTP (SMTP_2), ACAP, IMAP (IMAP_2), IRC, POP3, FTPS, LDAP, RDP (RDP_SSL), XMPP, CUSTOM
                (Notes: * SMTP_2 and IMAP_2 are second ways to use SMTP/IMAP, like RDP_SSL for RDP
                        * SMTP: use '--mx' for checking a mail-domain instead of a host)
                Please give us feedback (especially for FTPS, LDAP, RDP, CUSTOM)
                The STARTTLS_TYPEs 'ACAP', 'IRC' and 'CUSTOM' need the '--experimental' option, and please take care!
                You can use the STARTTLS_TYPE 'CUSTOM' to customize your own STARTTLS sequence including error handling, see '--starttls_phase[NUMBER]' and --starttls_error[NUMBER]
   ...

    --starttls_phase[NUMBER from 1..5]="VALUE" (VALUE might be an expression or a string)
                Customize the internal state machine to manage STARTTLS, you can use up to 5 phases:
                 1: set expression for 'receive data (RX)', e.g. ".?(?:^|\n)220\s"
                 2: set string for 'send data (TX)',        e.g. "EHLO o-saft.localhost\r\n"
                 3: set expression for RX,                  e.g. ".?(?:^|\n)250\s"
                 4: set string for TX,                      e.g. "STARTTLS\r\n"
                 5: set expression for RX,                  e.g. ".?(?:^|\n)220\s"
                For the TX phases 2 and 4 solely the escape sequences '\r', '\n', '\t' and '\x<00-ff>' are supported, e.g. "\r\n", "\x0d\x0a"
                It is recommended to use at least TX and RX (last RX to get data that does not belong to the handshake of SSL/TLS itself),
                furthermore you should use '--trace=3' when you start customizing.
                Please share your results with us (... via github).
                needs also '--starttls=CUSTOM', see above
                optional use of '--starttls_error[NUMBER]' to handle errors

    --starttls_error[NUMBER from 1..3]="EXPRESSION" (or '--starttls_err[NUMBER from 1..3]="EXPRESSION")
                Optional error handling for customized STARTTLS used in the RX phases (1, 3 and 5)
                 1: set expression for 'temporary unreachable (too many connections)', e.g. ".?(?:^|\n)(?:421|450)\s"
                 2: set expression for 'this SSL/TLS-Protocol is not supported',       e.g. ".?(?:^|\n)4[57]4\s"
                 3: set exptession for 'fatal Error/STARTTLS not supported',           e.g. ".*?(?:^|\n)(?:451|50[023]|554)\s"
                needs also '--starttls=CUSTOM' and '--starttls_phase[NUMBER]', see above

**Comment by maaaaz** [comment]
Hello @sslHello,

Wow thank for your work, I'll try it asap and let you know about it.

**Comment by sslHello** [comment]
Hi,
I'd like to let you know that I harmonized the input format of checkAllCiphers.pl with o-saft.pl and enabled both using customized starttls sequences. Furthermore I added the escape sequences '//' and '/e' for the --starttlsphase2 and 4. Finally some tracing is now nicer.
e.g. checkAllCiphers.pl --starttlsphase1=".?(?:^|\n)220\s" --starttlsphase2="EHLO o-saft.localhost\r\n" --starttlsphase3=".?(?:^|\n)250\s" --starttlsphase4="STARTTLS\r\n" --starttlsphase5=".?(?:^|\n)220\s" --starttlserror1=".?(?:^|\n)(?:421|450)\s" --starttlserror2=".?(?:^|\n)4[57]4\s" --starttlserror3=".*?(?:^|\n)(?:451|50[023]|554)\s" localhost:25 --starttls=custom --experimental --trace=3

**Comment by sslHello** [comment]
Thanks for the nice feature request. It has been implemeted in March 2016, I've tested it myself and it works fine. As I have not got any other feedback since then, I close the ticket now.
