### ISSUE TITLE
Packaging O-Saft as a standalone Windows executable

### ISSUE THREAD

**Issue by maaaaz** [OWASP/O-Saft#48]
Hello,

Just as `sslscan` and `sslyze`, do you think you could package `O-Saft` as a standalone Windows  (and even ELF) executable ?
As you may imagine, this is very convenient when you can't have your workstation on the audited network.

Cheers.

**Comment by EnDe** [comment]
Please remember: o-saft.pl is a script and not an executable. This have been done to avoid any special platform dependent packaging. A script is not an executable!

However, we think about to provide a "all-in-one-script" which at least contains our own modules ...

**Comment by maaaaz** [comment]
Of course it's a script, I just wanted to know you could manage to make an executable.
For instance, python scripts can be turned into standalone executables with `pyinstaller`, `py2exe` or `cx_freeze`. 
I just don't know if something similar exists for PERL script and, more importantly, would be reliable.

**Comment by EnDe** [comment]
Quick check with perl2exe from http://www.indigostar.com showed that it genereates a o-saft.exe with
   perl2exe o-saft.pl
Simple tests with o-saft.exe worked, butI  didn't test all commands and opetions.

**Comment by EnDe** [comment]
Documentation for building stand-alone executables added, see
  https://www.owasp.org/index.php/O-Saft/Documentation#Stand-alone_Executable
and
  o-saft.pl --help=INSTALL

Please let me know if this works, so I can close this issue.
