### ISSUE TITLE
osaft.pm contains joke code

### ISSUE THREAD

**Issue by pykoder** [OWASP/O-Saft#49]
Commits from 18 may are adding some obfuscated joke code to osaft.pm that tells "Alles Gut" and "Happy Birtday" when you try to run osaft. EnDe account hacked ? 

It should certainly be reverted, the joke is annoying fro people cloning the tool from repository (not my birthday). 

It's also quite frightening; what if it were some trojan setup code instead ? Maybe the github setting should be changed to a two stages validation process ?

**Comment by EnDe** [comment]
fixed
