### ISSUE TITLE
o-saft.pl +vulns exits non-zero when vulnerability is found

### ISSUE THREAD

**Issue by bbaassssiiee** [OWASP/O-Saft#50]
I run o-saft from Jenkins, if the script would fail on a vulnerability found, then the jenkins build could fail and I can sent an alert.

**Comment by EnDe** [comment]
do I understand correctly that you want to send an alert based on the result reported by o-saft?

# sh syntax:
o-saft.pl --no-warning --no-header +vulns youhost --legacy=compact | grep -q :no && echo alert

**Comment by bbaassssiiee** [comment]
I can live with:
grep -q :no && /bin/false
Then Jenkins has a failed build which can be notified like all others.

**Comment by EnDe** [comment]
please look close at the messages, may be you want:

   ... | grep -v '( *<<' | grep -q :no ...

**Comment by bbaassssiiee** [comment]
There is still some noise in the output:

Use of uninitialized value $version::VERSION in numeric lt (<) at ./o-saft.pl line 1712.
**WARNING: ancient perl has no 'version' module; version checks may not be accurate; at ./o-saft.pl line 1715.

**Comment by EnDe** [comment]
Sounds like your perl installtion uses an ancient version module,
please post the result of
  perl -Mversion -le 'print $version::VERSION'

--
"Use of uninitialized value $version::VERSION ..." is a bug, will be fixed.
"**WARNING: ancient perl has no 'version' module" is a hint, it will remain. Please filter this message yourself (**WARNING  are written on STDOUT).

Note: my experiance is that if you have an ancient version module (<0.77), other modules may also be outdated. o-saft can deal with these situation, but you get **WARNING messages and !!Hint messages. Hope they help ;-)

**Comment by bbaassssiiee** [comment]
Ok I fixed the 'version' , looks good. But I think I still want an exit code when one of the tests fails, or an option for that. Then i can clone, run, fail in jenkins without programming

**Comment by EnDe** [comment]
Can you please open a new issue for that. I'll mark it as enhancement then.
Thanks
