### ISSUE TITLE
Can't locate "get_sslversion"

### ISSUE THREAD

**Issue by bbaassssiiee** [OWASP/O-Saft#53]
My daily build fails since November 20th:

Can't locate object method "get_sslversion" via package "IO::Socket::SSL" at ./o-saft.pl line 2659

**Comment by EnDe** [comment]
ok, can you please post the version IO::Socket::SSL,
  perl -MIO::Socket::SSL -e 'print $IO::Socket::SSL::VERSION'

Meanwhile a quick fix is available at github (works if not run with --trace option)

**Comment by bbaassssiiee** [comment]
1.94 on Centos 7

**Comment by bbaassssiiee** [comment]
Works for me now.
