### ISSUE TITLE
Misleading "(0 (ok))" in output

### ISSUE THREAD

**Issue by fredomgc** [OWASP/O-Saft#55]
I created self-signed certificate for my localhost. Then I run following:

./o-saft.pl +check https://127.0.0.1/

In the output, there is this line, which is confusing for me:
Certificate is not self-signed:     	no **(0 (ok))**

Result is correct (value "no"), but what exactly means "**(0 (ok))**"? How should be this interpreted?

I briefly looked into source code of O-Saft and this looks like bug to me. If I understand correctly, "0" and "ok" are some default values, that should be outputed only in combination with cipher suite (?).

**Comment by EnDe** [comment]
This message looks strange indeed.
Just fixed a year-old bug 2 days ago https://github.com/OWASP/O-Saft/commit/1b2a8053ad756c6d584a543cf72824bc8033e74a
Can you please check if it still behaves this way. I expect now:
  Certificate is not self-signed:     	no (self signed certificate)

According the output form, please see: `o-saft.pl --help=results`

**Comment by fredomgc** [comment]
Still same output.
- I downloaded current branch "master"
- Then I typed: "./o-saft.pl +check https://127.0.0.1/"
- Here is screenshot of the output >> https://beta.ctrlv.cz/en/STis

**Comment by EnDe** [comment]
Fixed in https://github.com/OWASP/O-Saft/commit/f215912a2f22d012332c02cbefdd9a9cb5d2b002

Hoever, if you realy have a self-signed cert, o-saft.pl should report
  Certificate is not self-signed:     	no (self signed certificate)


Please confirm the fix.

**Comment by fredomgc** [comment]
Now output is:
Certificate is not self-signed: **yes**

But my certificate is (still) self-signed, i didn't change anything.

**Comment by EnDe** [comment]
Please use `echo|openssl s_client -connect 127.0.0.1:443` and post all lines starting with verify or Verify . Thanks.
You should see something like:

  CONNECTED(00000003)
  depth=0 C = ---snipp---
  verify error:num=18:self signed certificate
  verify return:1
