### ISSUE TITLE
Global symbol "$psha" requires explicit package name at ./o-saft.pl line 6093.

### ISSUE THREAD

**Issue by bbaassssiiee** [OWASP/O-Saft#56]
+ ./o-saft.pl --no-warning --no-header +vulns mydomain.com --legacy=compact
Global symbol "$psha" requires explicit package name at ./o-saft.pl line 6093.
BEGIN not safe after errors--compilation aborted at ./o-saft.pl line 6323.
Build step 'Execute shell' marked build as failure

**Comment by EnDe** [comment]
Fixed in https://github.com/OWASP/O-Saft/commit/124eac0bea33f133613c28177809c4a83fa7bcb4

**Comment by bbaassssiiee** [comment]
Confirmed by my daily build.

**Comment by EnDe** [comment]
thanks
