### ISSUE TITLE
uninitialized value $cfg{"ca_path"}

### ISSUE THREAD

**Issue by bbaassssiiee** [OWASP/O-Saft#63]
+ ./o-saft.pl --no-warning --no-header +vulns www.schiphol.nl --legacy=compact
Use of uninitialized value $cfg{"ca_path"} in string eq at ./o-saft.pl line 6370.
Use of uninitialized value $cfg{"ca_path"} in concatenation (.) or string at ./o-saft.pl line 1840.

**Comment by EnDe** [comment]
Thanks for reporting, fixed in https://github.com/OWASP/O-Saft/commit/d4b4aa0a46870a4bc5e6e3004a1e13c272fc94e8 .
