### ISSUE TITLE
o-saft.pl +cipher-dh: Use of uninitialized value $supported in pattern match (m//) at o-saft.pl line 5044

### ISSUE THREAD

**Issue by sslHello** [OWASP/O-Saft#66]
o-saft.pl +cipher-dh server:443 --nodns --v --header

produces several lines of the error message:
"Use of uninitialized value $supported in pattern match (m//) at o-saft.pl line 5044"
It still works, but the error appears.

Version Info:
=   module name            VERSION  found in
=   ----------------------+--------+------------------------------------------
    Net::SSLinfo           16.12.16 Net/SSLinfo.pm
    Net::SSLhello          16.06.12 Net/SSLhello.pm
    Ciphers
    osaft                  17.01.11 osaft.pm

Kind regards

**Comment by EnDe** [comment]
Fixed in [o-saft.pl](https://github.com/OWASP/O-Saft/commit/d8a6e1d0a66079e69341aaf616bb7088b50a980a)
