### ISSUE TITLE
Can't locate auto/Net/SSLeay/P_alpn_sele.al

### ISSUE THREAD

**Issue by bbaassssiiee** [OWASP/O-Saft#84]
Can't locate auto/Net/SSLeay/P_alpn_sele.al in @INC (@INC contains: . ./lib ./ ./lib . /bin /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ./o-saft.pl line 3580.

Didn't you setup CI on this project?

**Comment by EnDe** [comment]
I'm working on it. Fix comming soon ...
Can you please tell me which Net::SSLeay this is (o-saft.pl +version)?

**Comment by bbaassssiiee** [comment]
I run a daily CI on O-Saft, now it will mail you too when it fails.

**Comment by bbaassssiiee** [comment]
I will update my CI server libs

**Comment by EnDe** [comment]
fixed in [o-saft.pl](b3098e8f5859f2c8b963b48e14186d7c8569a66b)
