### ISSUE TITLE
Can't locate auto/Net/SSLeay/CTX_v2_new.al in @INC

### ISSUE THREAD

**Issue by EnDe** [OWASP/O-Saft#9]
When using +check or +cipher o-saft.pl exits with a perl error like:

Can't locate auto/Net/SSLeay/CTX_v2_new.al in @INC (@INC contains: /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at /usr/share/perl5/IO/Socket/SSL.pm line 1427

Probelm most likely is that the used openssl (and it's library libssl.so) does no support SSLv2, for example with openessl 1.0.x.

Workaround: use another libssl.so and openssl.so using --lib and --exe options.

Future version will detect missing functionality and switch it off automatically and also provide an option to disable SSLv2 checks.

**Comment by temple** [comment]
This @EnDe suggest does nothing for me if I'm still using current `VERSION 17.04.17` (at commit df44a3e98f79684c50aa6dd4bfc80d0c1125e3cc).

But If I checkout previous named version: "16.12.16" it works like a charm.

**Comment by EnDe** [comment]
@temple, you mean you can check SSL 2 with version 16.12.16, but not with 17.04.17?
